sudo: required
services:
  - docker

before_install:
  - docker build -t andrewtdinh/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true andrewtdinh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-1-374826361561"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"